done homework github.com/radiophysiker/otus-go/hw07_file_copying
radiophysiker/otus-go pull request #2
Opened 2021-05-09 12:08 UTC by radiophysiker

## Домашнее задание №7 «Утилита для копирования файлов»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-05-09 14:21 UTC, kulti requested changes
Дмитрий, хорошая работа со структурой кода и тестов 👍 Есть одна недоработка с прогрессом копирования. Попробуйте позапускать свою программу, чтобы увидеть проблему (test.sh тоже ее покажет).

2021-05-09 14:21 UTC, kulti commented on hw07_file_copying/copy.go
> +		totalAmountOfBytes = sourceFileSize - offset
Нужен ли в этом случае LimitReader?

2021-05-09 14:21 UTC, kulti commented on hw07_file_copying/copy.go
> +		totalAmountOfBytes = limit
Что будет, если limit больше размера файла?

2021-05-09 14:21 UTC, kulti commented on hw07_file_copying/copy.go
> +	}
Посмотрите на пример использования пакета pb для IO — https://github.com/cheggaaa/pb#progress-bar-for-io-operations.

2021-05-09 14:21 UTC, kulti commented on hw07_file_copying/copy_test.go
> +func TestCopyingProcess(t *testing.T) {
Не понял, чем этот тест принципиально отличается от предыдущего. Я бы сказал, что это даже вредный тест. Он тестирует внутреннее устройство публичного API и тем самым усложняет рефакторинг кода.

2021-05-09 14:21 UTC, kulti commented on hw07_file_copying/copy_test.go
> +		expectedError    error
Я рекомендую разделять позитивные и негативные тесты. Обычно у них разные сценарии, и смешивание двух сценариев внутри одного теста усложняет его код. Так же для негативных тестов может быть важен только какой-то один момент и тест получается очень простой, буквально из двух строк.

PS. expectedError никак не используется.

2021-05-09 16:12 UTC, radiophysiker commented on hw07_file_copying/copy.go
> +		totalAmountOfBytes = sourceFileSize - offset
А как ограничить длину копирования?

2021-05-09 16:13 UTC, radiophysiker commented on hw07_file_copying/copy.go
> +		totalAmountOfBytes = limit
Поправил

2021-05-09 16:13 UTC, radiophysiker commented on hw07_file_copying/copy.go
> +	}
Поправил.

2021-05-09 16:13 UTC, radiophysiker commented on hw07_file_copying/copy_test.go
> +		expectedError    error
Сделал разделение

2021-05-09 16:13 UTC, radiophysiker commented on hw07_file_copying/copy_test.go
> +func TestCopyingProcess(t *testing.T) {
Удалил

2021-05-10 07:48 UTC, kulti requested changes
Проблема в логике работы исправлена, но закралась другая потенциальная проблема из-за конвертации int64 <-> float64. Если ее исправить, то по логике работы все будет ок.

Если хочется баллы за чистоту кода, то надо немного изучить стандартную библиотеку и pb.

2021-05-10 07:48 UTC, kulti commented on hw07_file_copying/copy_test.go
> +	for {
Посмотрите на метод io.ReadAll.

2021-05-10 07:48 UTC, kulti commented on hw07_file_copying/copy_test.go
> +			t.Error(test.testCaseID, index, "expected error: ", test.expectedError)
Посмотрите метод t.Run. Также можно пересмотреть первое занятие про тестирование (конкретно раздел про табличные тесты).

2021-05-10 07:48 UTC, kulti commented on hw07_file_copying/copy_test.go
> +		os.Remove("testdata/temp.txt")
Этот код иногда может не выполняться, т.е. после тестов может оставаться мусор.

2021-05-10 07:48 UTC, kulti commented on hw07_file_copying/copy_test.go
> +			t.Error(test.testCaseID, index, "files are not equal")
Писать тесты через t.Error не самая безопасная практика. На занятии про тестирование про это подробно рассказывалось. Тут, вроде, ничего страшного. Если вы тут сознательно ставили t.Error, понимая все его опасности, и пришли к выводу, что ничего страшного, то 👍

2021-05-10 07:48 UTC, kulti commented on hw07_file_copying/copy.go
> +		totalAmountOfBytes = sourceFileSize - offset
А чему равен limit в этом случае? Что это значение означает?

2021-05-10 07:48 UTC, kulti commented on hw07_file_copying/copy.go
> +		totalAmountOfBytes = int64(math.Min(float64(limit), float64(sourceFileSize)))
При относительно больших значениях limit и sourceFileSize могут начаться ошибки «округления» при конвертации в float64 и обратно. Код выглядит опасно.

2021-05-10 07:48 UTC, kulti commented on hw07_file_copying/copy.go
> +	}
Не вижу. Все также ручная работа с буффером в цикле.

2021-05-15 12:53 UTC, radiophysiker commented on hw07_file_copying/copy.go
> +		totalAmountOfBytes = sourceFileSize - offset
вычислим суммарное количество байтов для копирования данное значение нужно для прогресса и для задания лимита для копирования

2021-05-15 12:53 UTC, radiophysiker commented on hw07_file_copying/copy.go
> +	}
поправил

2021-05-15 12:53 UTC, radiophysiker commented on hw07_file_copying/copy_test.go
> +	for {
Поправил

2021-05-15 12:53 UTC, radiophysiker commented on hw07_file_copying/copy_test.go
> +			t.Error(test.testCaseID, index, "expected error: ", test.expectedError)
Пересмотрел поправил

2021-05-15 12:54 UTC, radiophysiker commented on hw07_file_copying/copy_test.go
> +			t.Error(test.testCaseID, index, "files are not equal")
Поправил на fatal

2021-05-15 12:54 UTC, radiophysiker commented on hw07_file_copying/copy.go
> +		totalAmountOfBytes = int64(math.Min(float64(limit), float64(sourceFileSize)))
Исправил

2021-05-17 04:43 UTC, kulti approved these changes
Теперь решение корректное 👍 Здорово, что довели его до ума. ДЗ принято — 9/10.

2021-05-17 04:43 UTC, kulti commented on hw07_file_copying/copy.go
> +	_, err := io.Copy(w, barReader)
Еще есть метод `io.CopyN`.

2021-05-17 04:46 UTC, merged